#!/bin/sh
echo Building GCS...
[ -f table.gcs ] || python python/gcs.py build samples/words.english
echo Querying GCS...
python python/gcs.py query affect afect school skool circumvolution circumvollution
